### ISSUE TITLE
Prometheus::Client::Registry::AlreadyRegisteredError error

### ISSUE THREAD

**Issue by pablocrivella** [yabeda-rb/yabeda-prometheus#9]
I haven't been able to set up the following combination of yabeda gems:

```
gem "yabeda-rails"
gem "yabeda-prometheus"
gem "yabeda-puma-plugin"
gem "prometheus-client", "~> 0.9.0"
```
When I run `bin/rails s`

I get the following error:

```
~/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/prometheus-client-0.9.0/lib/prometheus/client/registry.rb:26:in `block in register': rails_requests_total has already been registered (Prometheus::Client::Registry::AlreadyRegisteredError)
```

**Comment by Envek** [comment]
Hello! Can you please provide a little bit more info on how to reproduce this? I wasn't able to catch it yet.

**Comment by pablocrivella** [comment]
I tried to reproduce the issue using: https://github.com/yabeda-rb/example-prometheus/tree/master/rails_app

To be able to install the gems I had to update `mini_racer` due to a `Gem::Ext::BuildError: ERROR: Failed to build gem native extension.` error.

After that, when I ran `bin/rails s` I got the same error immediately. So I guess this could be an issue with my current os: MacOS Catalina.
PS. Already having some issues with the spring gem and Catalina.

**Comment by i5okie** [comment]
having same issue

**Comment by i5okie** [comment]
To reproduce:
```
git clone https://github.com/yabeda-rb/example-prometheus.git
cd example-prometheus/rails_app
bundle install
rails db:migrate
rails db:seed
rails s
=> Booting Puma
=> Rails 5.2.2 application starting in development
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	61: from bin/rails:4:in `<main>'
	60: from bin/rails:4:in `require'
	59: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
	58: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
	57: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
	56: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	55: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	54: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	53: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `perform'
	52: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `tap'
	51: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	50: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:51:in `start'
	49: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	48: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	47: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:27:in `app'
	46: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	45: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	44: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	43: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	42: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	41: from config.ru:in `<main>'
	40: from config.ru:in `new'
	39: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	38: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	37: from config.ru:3:in `block in <main>'
	36: from config.ru:3:in `require_relative'
	35: from /Users/ivanp/code/example-prometheus/rails_app/config/environment.rb:5:in `<top (required)>'
	34: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	33: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	32: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	31: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	30: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	29: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	28: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	27: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	26: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	25: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	24: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	23: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	22: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	21: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	20: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
	19: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	18: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
	17: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	16: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	15: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	14: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
	13: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-rails-0.1.1/lib/yabeda/rails/railtie.rb:9:in `block in <class:Railtie>'
	12: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-rails-0.1.1/lib/yabeda/rails.rb:23:in `install!'
	11: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-0.1.2/lib/yabeda/dsl.rb:19:in `configure'
	10: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-0.1.2/lib/yabeda/dsl.rb:19:in `class_exec'
	 9: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-rails-0.1.1/lib/yabeda/rails.rb:26:in `block in install!'
	 8: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-0.1.2/lib/yabeda/dsl.rb:38:in `counter'
	 7: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-0.1.2/lib/yabeda/dsl.rb:57:in `register'
	 6: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-0.1.2/lib/yabeda/dsl.rb:57:in `each'
	 5: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-0.1.2/lib/yabeda/dsl.rb:58:in `block in register'
	 4: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-0.1.2/lib/yabeda/base_adapter.rb:8:in `register!'
	 3: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yabeda-prometheus-0.1.4/lib/yabeda/prometheus/adapter.rb:17:in `register_counter!'
	 2: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/prometheus-client-0.8.0/lib/prometheus/client/registry.rb:24:in `register'
	 1: from /Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/prometheus-client-0.8.0/lib/prometheus/client/registry.rb:24:in `synchronize'
/Users/ivanp/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/prometheus-client-0.8.0/lib/prometheus/client/registry.rb:26:in `block in register': rails_requests_total has already been registered (Prometheus::Client::Registry::AlreadyRegisteredError)
```

**Comment by i5okie** [comment]
Issue resolved for me.
I've added `yabeda-rails` to Gemfile, and had config/initizalizers/yabeda.rb with`Yabeda::Rails.install!` which is not necessary.
Removing that from initializers resolves this issue for me.

**Comment by pablocrivella** [comment]
You are right @i5okie removing `Yabeda::Rails.install!` fixes the issue! Thanks 👏

**Comment by Envek** [comment]
Thank you for the investigation, folks!

It doesn't really needed because `yabeda-rails` does all the magic automatically.
